package com.thinklogics_backend.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Entity
@Table(name = "job_descriptions") // Define the table name
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class JobDescription {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Specify the primary key and its generation strategy

    private String date;
    private String month;
    private String jobTitle;

    @ElementCollection
    @CollectionTable(name = "responsibilities", joinColumns = @JoinColumn(name = "job_description_id"))
    @Column(name = "responsibility")
    private List<String> responsibilities;

    @ElementCollection
    @CollectionTable(name = "requirements", joinColumns = @JoinColumn(name = "job_description_id"))
    @Column(name = "requirement")
    private List<String> requirements;

    // Constructors and setters (getters are generated by Lombok)
}
