package com.thinklogics_backend.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.util.List;

@Document(collection = "job_descriptions") // Specify the collection name in MongoDB
@Data
@NoArgsConstructor
@AllArgsConstructor
public class JobDescription {

    @Id
    private String id; // Specify the primary key

    private String date;
    private String month;
    private String jobTitle;

    @Field("responsibilities") // Optional: Define the field name in MongoDB
    private List<String> responsibilities;

    @Field("requirements") // Optional: Define the field name in MongoDB
    private List<String> requirements;

    // Constructors and setters (getters are generated by Lombok)
}
